### ISSUE TITLE
error during execution of command:"sudo bin/gbuild ../litecoin/contrib/gitian-descriptors/deps-win32.yml"

### ISSUE THREAD

**Issue by BhumikaB** [litecoin-project/litecoin#567] opened 2018-12-21 10:25 UTC
stopping target if it is up
Connection timed out during banner exchange
Killing target since it did not shutdown within 10 seconds
Making a new image copy
Formatting 'target-precise-amd64.qcow2', fmt=qcow2 size=11811160064 backing_file=base-precise-amd64.qcow2 encryption=off cluster_size=65536 lazy_refcounts=off refcount_bits=16
Starting target
Checking if target is up..............................
Connection timed out during banner exchange
bin/gbuild:21:in `system!': failed to run on-target true (RuntimeError)
	from bin/gbuild:74:in `build_one_configuration'
	from bin/gbuild:309:in `block (2 levels) in <main>'
	from bin/gbuild:304:in `each'
	from bin/gbuild:304:in `block in <main>'
	from bin/gbuild:302:in `each'
	from bin/gbuild:302:in `<main>'

**Comment by thrasher-** [comment] 2019-01-03 00:12
Closing this as it is a duplicate of https://github.com/litecoin-project/litecoin/issues/570.

**Closed by thrasher-** 2019-01-03 00:12 UTC
