### ISSUE TITLE
Zero conf getbalance regression in Bitcoin 0.10 

### ISSUE THREAD

**Issue by wtogami** [litecoin-project/litecoin#201] opened 2015-06-12 21:49 UTC
See Bitcoin PR #6276 for a proposed patch to fix a getbalance zero conf behavior regression that shipped in Bitcoin 0.10.  We really should fix this before we ship our first 0.10 as it confuses some existing uses of RPC and breaks expected behavior for some users.

Please test this behavior both with and without this patch, and compare to our 0.8 behavior.

Let's try to avoid merging it ourselves until after Bitcoin master has merged it.  They may come up with a better fix.

**Comment by thrasher-** [comment] 2015-06-13 05:39
Patch works as intended:

0.8.7.5 2 LTC sent

before transaction
15:07:22 getbalance *
15:07:22 0.49900000

after transaction 0 conf
15:07:26 getbalance * 0
15:07:26 0.49900000

after transaction 0 conf
15:07:45 getbalance *
15:07:45 0.49900000

after transaction 1 conf
15:10:36 getbalance * 1
15:10:36 2.49900000

after transaction 1 conf
15:10:38 getbalance *
15:10:38 2.49900000

0.10.2.2 without patch .5 LTC sent

before transaciton
21:54:33 getbalance *
21:54:33 99.00680006

after transaction 0 conf
21:55:53 getbalance * 0
21:55:53 99.00680006

after transaction 0 conf
21:55:55 getbalance *
21:55:55 99.00680006

after transaction 1 conf
21:58:12 getbalance * 1
21:58:12 99.50680006

after transaction 1 conf
21:59:54 getbalance *
21:59:54 99.50680006

0.10.2.2 with patch 1 LTC sent

before transaction
22:29:40 getbalance *
22:29:40 97.50580006

after transation 0 conf
22:31:07 getbalance * 0
22:31:07 98.50580006

after transaction 0 conf
22:31:20 getbalance *
22:31:20 97.50580006

after transaction 1 conf
22:33:52 getbalance * 1
22:33:52 98.50580006

after transaction 1 conf
22:34:29 getbalance *
22:34:29 98.50580006

**Comment by thrasher-** [comment] 2015-06-15 09:31
The PR has been merged upstream and into Litecoin master-0.10. This issue has been resolved.

**Closed by thrasher-** 2015-06-15 09:31 UTC
