### ISSUE TITLE
Qt 5.15 warnings

### ISSUE THREAD

**Issue by broros** [litecoin-project/litecoin#691] opened 2021-01-12 01:08 UTC
getting lots of warnings related to qt 5.15 on osx

'''
warning: 'width' is deprecated: Use QFontMetrics::horizontalAdvance [-Wdeprecated-declarations]
warning: 'mapped' is deprecated: Use QSignalMapper::mappedInt(int) instead [-Wdeprecated-declarations]
'''

**Comment by DumbGameMaker** [comment] 2021-02-14 17:38
duplicate of #689

**Closed** 2021-05-04 09:02 UTC
