### ISSUE TITLE
Build failing on Ubuntu 16.04 after recent commit 865c17dd3573aa8637ba0bc32fdcf754387a481c

### ISSUE THREAD

**Issue by MintyFresh** [litecoin-project/litecoin#252] opened 2016-09-17 19:54 UTC
Having problems compiling after the most recent commit. I've redirected STDOUT and STDERR to a text file, which I've put up at http://pastebin.com/LkgS4UyS in case it's helpful.

Here is how I'm building:

Standard Ubuntu 16.04 server installation (I think it may technically be 16.04.1).

Build Berkeley DB:
`wget "http://download.oracle.com/berkeley-db/db-4.8.30.NC.tar.gz"`
`tar --extract --ungzip --verbose --file db-4.8.30.NC.tar.gz`
`cd db-4.8.30.NC/build_unix/`
`../dist/configure --enable-cxx --disable-shared --with-pic --prefix=${BDB_PREFIX}
make install`

Build Litecoind:
`BASEDIR="/home/myusername/cryptod"`
`sudo apt-get install --assume-yes build-essential libtool autotools-dev autoconf pkg-config libssl-dev libboost-all-dev`
`mkdir --parents ${BASEDIR}/run/litecoin`
`mkdir --parents ${BASEDIR}/build/`
`cd ${BASEDIR}/build`
`git clone https://github.com/litecoin-project/litecoin.git`
`cd ${BASEDIR}/build/db-4.8.30.NC/build_unix/`
`../dist/configure --enable-cxx --disable-shared --with-pic --prefix=$BDB_PREFIX`
`make install`
`cd ${BASEDIR}/build/litecoin`
`./autogen.sh`
`./configure LDFLAGS="-L${BDB_PREFIX}/lib/" CPPFLAGS="-I${BDB_PREFIX}/include/" --without-gui`
`make`
`sudo make install`

So, doing it just like this has been working fine up until yesterday. Now, that process results in the issue shown in the pastebin

If I do a `git checkout -b minus-one HEAD~1` before running `make`, everything builds as expected.

I hope I've enough information. Let me know if there's anything else I can provide to help debug this. I also apologize if there's just something I'm doing wrong here.

**Comment by losh11** [comment] 2016-09-22 21:11
Hey, I'll fork this repository and add Travis-Cl to see if it also reports the same error message. I'll ask someone to take a look at this, because the last commit was a PR which was intended to fix builds for people running arch-linux.

**Comment by zhumingu** [comment] 2016-09-26 15:15
+1. on ubuntu 14.04make error too

**Comment by abrkn** [comment] 2016-10-05 20:53
Same on 16.04

**Comment by EtherSecAgent** [comment] 2016-10-13 03:31
same on minimal image, been busting my head on this all week

**Comment by MintyFresh** [comment] 2016-10-21 19:32
What's the error? If you followed the commands in the OP, including git checkout -b minus-one HEAD~1 it should work.

**Comment by karter18** [comment] 2016-10-21 19:48
testpool@ubuntu:~$ cd db-4.8.30.NC/build_unix/
testpool@ubuntu:~/db-4.8.30.NC/build_unix$ ../dist/configure --enable-cxx --disable-shared --with-pic --prefix=${BDB_PREFIX} make install
configure: WARNING: you should use --build, --host, --target
configure: WARNING: you should use --build, --host, --target
checking build system type... Invalid configuration `make': machine `make' not recognized
configure: error: /bin/bash ../dist/config.sub make failed

**Comment by MintyFresh** [comment] 2016-10-22 04:22
That problem doesn't really look like it pertains to this issue, or even Litecoin. You're running into issues just building Berkeley DB 4.8. I'm happy to offer what help I can, but I think we should take the discussion elsewhere since this thread is for a separate issue.

My best idea would be to get on Bitcointalk forums. You can hit me up there if you like, my username is OldSpurty.

Without knowing more, it's hard to say what's going wrong. How did you assign the variable ${BDB_PREFIX}?

**Comment by karter18** [comment] 2016-10-22 11:22
hi,

im trying to build a litecoin unomp pool but i am gettung errors on unbuntu server 16.04. so found this guide that i thought would fix the issue. i will get on bitcoin talk.

**Comment by thrasher-** [comment] 2016-10-26 00:56
Thanks @MintyFresh, a commit https://github.com/litecoin-project/litecoin/commit/40ce41c006787dc4a2e3b17f7abbaf8ff56c45e7 has been pushed to fix this problem :)

@karter18 if you have Berkely DB 4.8 installed, try:

./autogen.sh
./configure && make

I'm going to close this as it relates to a different problem, but please feel free to open up a separate issue.

**Closed by thrasher-** 2016-10-26 00:56 UTC

**Comment by fuscata** [comment] 2018-04-11 20:11
i want fork and make litecoin system. I want know all sodu file list.
can you tell me litecoin of all sudo file list?
