### ISSUE TITLE
got no views on my issue, so here it is. issue quite important it terminates my whole process

### ISSUE THREAD

**Issue by TheAwesomeGuy47** [litecoin-project/litecoin#731] opened 2021-06-01 22:15 UTC
https://github.com/litecoin-project/litecoin/issues/705

**Comment by thrasher-** [comment] 2021-06-10 08:15
Duplicate of https://github.com/litecoin-project/litecoin/issues/705

**Closed by thrasher-** 2021-06-10 08:15 UTC
